### ISSUE TITLE
重发似乎有bug.

### ISSUE THREAD

**Issue by 625781186** [huaSoftware/chat#5]
![image](https://user-images.githubusercontent.com/30521429/69883301-731d6e80-130e-11ea-84b8-e44146ee9df0.png)
## bug复现  :
我主动断线之后发送, 然后提示发送失败 , 接着连线,  点红X重新发送 , 然后退出房间 , 再进入.

**Comment by huaSoftware** [comment]
> ![image](https://user-images.githubusercontent.com/30521429/69883301-731d6e80-130e-11ea-84b8-e44146ee9df0.png)
> 
> ## bug复现 :
> 我主动断线之后发送, 然后提示发送失败 , 接着连线, 点红X重新发送 , 然后退出房间 , 再进入.

前端增加了链接错误事件来处理此问题
