### ISSUE TITLE
前端和后端似乎没做xss防范？

### ISSUE THREAD

**Issue by 625781186** [huaSoftware/chat#6]
![image](https://user-images.githubusercontent.com/30521429/71524736-d39dcc80-2909-11ea-8b34-4a406283df48.png)

**Comment by huaSoftware** [comment]
前端使用的是vue，可以通过使用xss库来防止xss攻击，当然，我更希望他们来攻击，起码证明这个项目还活着。https://www.cnblogs.com/1032473245jing/p/11929277.html

**Comment by 625781186** [comment]
存储型的xss靠前端没用的 , 可以用mitmproxy之类工具的本地代理替换掉 .
需要在后端处理.
